project:
  type: website
  output-dir: docs
  preview:
    port: 4202
  render:
    - "*.qmd"
  resources:
    - "img"

execute:
  freeze: auto

website:
  title: "CASA Computing Environment"
  image: "img/CASA_Logo_no_text.png"
  repo-url: https://github.com/jreades/sds_env/
  repo-actions: [issue]
  favicon: "/img/favicon.ico"
  open-graph:
    locale: en_GB
    site-name: "Spatial Data Science Environment"
  page-navigation: true
  reader-mode: true
  page-footer: 
    left: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 2022–2025, Jon Reades"
    center: "![](/img/favicon-16x16.png){.height:10px} CASA Computing Environment"
    right: 
      - icon: github
        href: https://github.com/jreades/sds_env
      - icon: twitter 
        href: https://twitter.com/CASAUCL
  navbar:
    background: primary
    number-depth: 2
    search: true
    logo: "/img/CASA_Logo_no_text.png"
    collapse: true
    collapse-below: md
    left:
      - sidebar:setup
      - sidebar:postinstall
      - sidebar:skills

  sidebar:
    - id: setup
      title: "Installation"
      style: "docked"
      collapse-level: 2
      background: light
      contents:
        - text: "Step 1. Health Check"
          href: setup/health.qmd
        - text: "Step 2. Base Utilities"
          href: setup/base.qmd
        - text: "Step 3. Installation"
          href: setup/installation.qmd
        - text: "All-In-One"
          href: setup/install_fest.qmd
        - text: "Common Problems"
          href: setup/problems.qmd
        - text: "About Virtualisation"
          href: setup/virtualisation.qmd

    - id: postinstall
      title: "Post-Installation"
      contents:
        - post/git.qmd
        - post/markdown.qmd
        - post/advanced.qmd

    - id: skills
      title: "Soft Skills"
      contents:
        - skills/attention.qmd
        - skills/reading.qmd
        - skills/thinking.qmd
        - skills/help.qmd

highlight-style: pygments

format:
  html:
    theme: 
      - minty
      - css/casa-report.scss
      - css/casa-web.scss
    code-copy: true
    code-link: true
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: true
