---
title: "Git & GitHub"
author: "Jon Reades"
date: last-modified
---

Git is a 'version control system', which is a fancy way of saying that it has the potential to store a complete, line-by-line history of your work... so long as it's in a plain-text format like [Markdown](./markdown.qmd) or Python/R code files. 

Git keeps all of this history on your computer every time you 'commit' the changes you've told it about by 'adding' changed files. With GitHub you can then synchronise these changes to their servers so that you have a full backup (code and content are no longer just on your computer), publish a web site like this one (via github.io), or collaborate with other people (via public or shared 'repositories'). 

While it is not necessary that you learn all about how GitHub works *now*, it will be really helpful if you can get yourself set up with a GitHub account and install Git locally so that you're ready to get when we start the term.

{{< include _git.qmd >}}

## Installing Git

In many cases (especially if you use a Mac) you may find that Git is already installed, you just didn't know it. For all other cases, you should be able to install Git easily; however, you can always follow along with GitHub's [own instructions](https://github.com/git-guides/install-git) for installing Git on your computer. 
