# To install/reinstall the environment:
#   conda-env create -f conda.install.yml
# To deal with issues reported by missing mamba solver:
#   https://github.com/ContinuumIO/anaconda-issues/issues/13353#issuecomment-2260475729
#   OR:
#   conda install -c conda-forge --solver=classic ...
#
channels:
  - conda-forge
dependencies: 
  - black # Supports code formatter labextension
  # - bokeh
  - clustergram
  - contextily
  - cython
  - descartes
  - flake8 # Style enforcement
  - numpy
  - scipy 
  - pandas 
  - pyogrio 
  - shapely 
  - pyproj
  - packaging
  # - cmake<3.20 # -- Thought this might fix issues, but no
  - matplotlib
  - matplotlib-base 
  - mapclassify
  - folium
  - geopy 
  # - ipyleaflet # Already in jupyter-minimal
  - ipyparallel
  # - ipympl # Already in jupyter-minimal
  - ipywidgets
  # - jupyter_bokeh # Forces significant downgrade of jupyterlab
  - jupyterlab_code_formatter # Supports labextension
  - jupyterlab-geojson
  - jupyterlab-variableinspector
  # - jupyter-lsp-python # Already in jupyter-minimal
  # - jupytext # Already in jupyter-minimal
  - legendgram 
  - lxml
  # - mgwr # -- Some problem here
  # - momepy # -- Some problem here
  - openpyxl
#   #- osmnx
  - palettable 
  - pip: # Adds about 500MB
    - geopandas[all]
    - datashader # -- Some problem here
    - pointpats # -- Some problem here
    - pyarrow # -- Some problem here
    # - libgdal-arrow-parquet
    - pysal # -- Possible problem
    - duckdb # -- Possible problem
    - spatialpandas # -- Possible problem
    # - esda # (alternative to PySAL stuff)
    # - joypy
    - matplotlib-scalebar 
  # - pointpats
  # - libgdal-arrow-parquet # -- Possible problem
  - polars
  - plotly
  - pyogrio
  - qgrid # Interactive grid for pandas DataFrames
  - rasterio
  - rasterstats
  - rio-cogeo
  - rioxarray
  - scikit-learn
  - seaborn
#   - statsmodels # Already in jupyter-minimal
  - tabulate  # For exporting from pandas to markdown
#   - tzlocal 
  #- xarray
  #- xvec
  # - xarray-spatial # -- Possible problem
  # - xarray_leaflet # -- Possible problem
  - xlrd
  - xlsxwriter
  # - ydata-profiling
