# Code Camp

Prior to (re)joining CASA from the [Department of Geography](https://www.kcl.ac.uk/geography) at [King's College London](htts://www.kcl.ac.uk/), [Dr. Mic Ferretti](https://mobile.twitter.com/miccferr/), [Dr. Zara Shabrina](https://twitter.com/zarashabrina), [Dr. James Millington](https://twitter.com/jamesmillington), and I developed [Code Camp](https://kingsgeocomputation.org/teaching/code-camp/code-camp-python/).

[Code Camp](https://kingsgeocomputation.org/teaching/code-camp/code-camp-python/) provides a gentle introduction to the basics of programming in Python. Across ten sessions you will learn about syntax, variables, 'simple' data structures such as lists and dictionaries, and about the fundamentals of writing functions for reusable code. The sessions are entirely self-led: you should follow along at your own pace and remember that 'it's a marathon, not a sprint'. **Don't cram it all into the last week of summer holidays!**

Students from previous years have repeatedly said that completing [Code Camp](https://kingsgeocomputation.org/teaching/code-camp/code-camp-python/) helped them to feel more ready for the *Foundations of Spatial Data Science* module, enabling them to do better on assessments and on the programme as a whole.

So please, **complete [Code Camp](https://kingsgeocomputation.org/teaching/code-camp/code-camp-python/)** by the start of term and, if possible, go through the materials more than once!