# Computer Health Check

When answering the questions below, 'your computer' is the machine on which you plan to do the programming. You will also have some ability to run code remotely on UCL's JupyterHub or on Google Collab (see [No Install](./no_install.qmd)), but you will find that limitations in processing power on these cloud platforms can make this a frustrating experience.

## Hardware Requirements

We try to support as many different configurations as possible, but there is *no* programming environment that installs and runs seamlessly on *all* computers. However, in our experience the students **most likely to encounter problems** share one or more of the following:

1. Your computer 8GB or less of RAM.
2. Your computer has less than 20GB of free disk space remaining.

Read on below to check what specification you have...

### MacOS

You will need to look up:

- How much RAM does your _main_ computer have? [Help for Mac](https://www.macworld.co.uk/how-to/mac/much-ram-need-more-3793418/).
- How much free disk space does your _main_ computer have? [Help for Mac](https://www.macworld.com/article/2972775/how-to-check-a-mac-free-hard-drive-space.html).

### Windows

You will need to look up:

- How much RAM does your _main_ computer have? [Help for Windows](https://www.howtogeek.com/435644how-to-see-how-much-ram-is-in-your-pc-and-its-speed/).
- How much free disk space does your _main_ computer have? [Help for Windows](https://www.lifewire.com/how-to-check-free-hard-drive-space-in-windows-2619187).

### Linux

We're going to assume that you know what you're doing. If you want a recommendation, we'd probably go with the latest Ubuntu desktop release.

### Recommendations

If you are looking for a recommendation as to what to buy:

1. Don't worry about getting the fastest chip, get as much RAM as you can. You should aim for 32GB of RAM, but get more if you can afford it.
2. Don't worry about getting the biggest hard drive, get the fastest one you can. You should get a SSD (Solid State Drive), but get a M2 type SSD if you can afford it and it's available for your system.
3. Only after you've sorted this out should you look for the fastest chipset that's still within your budget.

Should you buy a Windows, Linux, or Apple machine? You should probably stick with whatever you're familiar with since learning your way around a new Operating System while *also* learning to code is just raising the bar unnecessarily. Around CASA we use a mix of all three, and you can probably find as many opinions as there are staff members.

::: {.callout-tip}
## Saving Money

Two easy things to do to save money on a new machine are:

1. Unless there is a specific reason to do so (e.g. getting a system with Apple's M1/M2 chip), don't buy the latest machine, buy a model from earlier in the year/the previous year instead and upgrade the RAM and hard drive instead.
2. Only buy the machine when you have access to a student discount. The discount for Apple computers is relatively modest (ca. 10%) compared to 'back to school' offers for Windows machines, but as the Brits would say: even 10% is better than a kick in the teeth! 

:::

## Software Requirements

We try to support as many different configurations as possible, but there is *no* programming environment that installs and runs seamlessly on *all* computers. However, in our experience the students **most likely to encounter problems** share one or more of the following:

1. Your computer runs Windows 10 Home or older, or 
2. Your computer runs MacOS 10.13 (High Sierra) or older.

As long as your computer is running one of the last two major releases of the Operating System you should encounter few issues.

### MacOS

You will need to look up:

- What Operating System and Version is your _main_ computer running? [Help for Mac](https://support.apple.com/en-gb/HT201260).

### Windows

You will need to look up:

- What Operating System and Version is your _main_ computer running? [Help for Windows](https://support.microsoft.com/en-gb/help/13443/windows-which-version-am-i-running).

### Recommendations

If you are using a Mac then your system should have the option to update to the latest version of the MacOS at no charge. If you are unable to update then it is likely that you have an older machine that is not fully supported by the most recent Operating System and, in all probability, you will also encounter issues running the programming environment.

If you are using a Windows PC then try to update to either Windows 11 or to Windows 10 Pro as this will 'unlock' additional features that are useful for supporting the programming environment. As a student you are likely to qualify for significantly cheaper/free updates, so make sure you do this when you have access to a discount.

## System Updates

Now that you know your computer is 'up-to-spec', please ensure that your computer is fully up-to-date with all Operating System and application updates before following any of the *other* steps in this brief guide to getting started. 

::: {.callout-warning}
## Automatic Updates

Once you have [installed](./env.qmd) the programming environment we *strongly* recommend that you **turn off automatic updates** for your computer until the end of the academic year. This is not to say that you should *not* install security and other updates over the course of the year, but to emphasise that it should be **at a time of your choosing**. In previous years, students' computers have automatically updated to a whole new operating system version two nights before an assessment deadline, breaking existing code and causing lots of needless stress.

:::