
Podman requires you to create a virtual machine with user-specified characteristics *before* you can run an image. You can think of this as specifying the 'hardware' of the computer before you buy it (How much RAM? How big a hard drive? And so on.). In principle, this means that you can have more than one valid configuration at a time which would allow you to tune each virtual machine to your needs (one machine could have a lot of memory, another a lot of storage). 

Here's the quick-start version:

:::: {.panel-tabset}

### Apple MacOS

In iTerm2 you simply type (hitting Enter after each line):
```bash
podman machine init
podman machine start
```

### Windows

In the Windows Terminal you *should* be able to simply type (hitting Enter/Return after each line):
```bash
podman machine init
podman machine start
```

::: {.callout-warning}
### Unable to Run

In a small number of cases on Windows we've had error messages about permissions and been unable to `start` the machine that was created using `init`. In that case, it seems that you just need to create a new, named virtual machine (e.g. `podman machine init myvm`) and then change the default machine.

:::

::::

If you'd like to read more about fine-tuning your Podman machine we've [got a page for that](./podman_conf.qmd).
