---
title: "Git & GitHub"
author: "Jon Reades"
date: "9/7/2023"
---

Git is a 'version control system', which is a fancy way of saying that it has the potential to store a complete, line-by-line history of your work... so long as it's in a plain-text format like [Markdown](./markdown.qmd) or Python/R code files. Git updates all of this history on your computer every time you 'commit' the changes you've told it about by 'adding' a file. With GitHub you can then synchronise these changes so that you have a full backup (code and content are no longer just on your computer), publish a web site (via github.io), or collaborate with other people (via public, shared 'repositories'). 

While it is not necessary that you learn all about how GitHub works *now*, it will be really helpful if you can get yourself set up with a GitHub account and install Git locally so that you're ready to get when we start the term.

## Get a GitHub Account

You will want to go to [GitHub.com](https://github.com/) and then click the `Sign up` button at the top right. Follow the instructions for creating a new account from there.

::: {.callout-tip}
## Use Your Personal Account

Although you can always change it later (so if you've opened your GitHub account using your UCL email don't panic!), you may find it easier to:

- Open a GitHub account using a personal email address to which you expect to always have access.
- Then associate your UCL email address to this GitHub account so that you gain from any educational benefits offered by GitHub (there are some around private respositories and so on).
:::

## Install Git Locally

You can follow along with GitHub's [own instructions](https://github.com/git-guides/install-git) for installing Git on your own computer. In many cases (especially if you use a Mac) you may find that Git is already installed, you just didn't know it.
